<a href="https://colab.research.google.com/github/Sarthak-Rajvaidya/Tensors-in-pytorch-deep-dive/blob/main/tesnors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
#To check is GPU is available or not
if torch.cuda.is_available():
  print("GPU is available")
  print(f"USing GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
USing GPU:Tesla T4


CREATING A **TENSOR** **bold text**

In [3]:
#uisng empty
a =torch.empty(2,3)

In [4]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand - To create random values in between 0 to 1
torch.rand(2,3)

tensor([[0.2452, 0.3444, 0.1098],
        [0.2010, 0.1069, 0.8916]])

In [13]:
#manual seed:- to get same random valus for differnet users:-\
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
#using tensor - custom apne manapasand
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

**TENSORS** **SHAPE**

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])